class Solution {
public:
    // The idea is to store the frequency of all the gcd values ending at each index 'i'. 
    // In a strictly randomized sequence or a specialized construction where all elements are distinct, 
    // the GCD sequence generated by extending subarrays from left to right can change at most 30-40 times 
    // for any starting element, bounded only by the physical constraints of factorization.

    // You can reach up to 510 unique GCDs if you intentionally construct the array using highly 
    // composite, co-prime, or mathematically-paired values.

    // Since the maximum value in the array is nums[i]<=10^9, 
    // the maximum possible number of distinct divisors for any single number in the array is 1344 (735134400).

    int subarrayGCD(vector<int>& nums, int k) {
        int n=nums.size();
        unordered_map<int,int>freq;
        int ans=0;
        for(int i=0;i<n;++i)
        {
            unordered_map<int,int>currFreq;
            for(auto &x:freq)
            {
                int gcdVal=__gcd(x.first, nums[i]);
                if(gcdVal==k) ans+=freq[x.first];

                currFreq[gcdVal]+=freq[x.first];
            }
            if(nums[i]==k) ans++;
            currFreq[nums[i]]++;

            freq.clear();
            freq=currFreq;
        }
        return ans;
    }
};